{{- if .Values.sso.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anything-llm.fullname" . }}-sso-config
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sso
data:
  POSTGRES_HOST: {{ .Values.sso.config.POSTGRES_HOST | quote }}
  POSTGRES_USER: {{ .Values.sso.config.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.sso.config.POSTGRES_DB | quote }}
  KEYCLOAK_ANYTHING_LLM_ID_CLAIM: {{ .Values.sso.config.KEYCLOAK_ANYTHING_LLM_ID_CLAIM | quote }}
  KEYCLOAK_ANYTHING_LLM_USERNAME_CLAIM: {{ .Values.sso.config.KEYCLOAK_ANYTHING_LLM_USERNAME_CLAIM | quote }}
  KEYCLOAK_ANYTHING_LLM_GROUP_CLAIM: {{ .Values.sso.config.KEYCLOAK_ANYTHING_LLM_GROUP_CLAIM | quote }}
  KEYCLOAK_ANYTHING_LLM_GROUP_CORRELATIONS: {{ .Values.sso.config.KEYCLOAK_ANYTHING_LLM_GROUP_CORRELATIONS | quote }}
  ANYTHING_LLM_URL: {{ .Values.sso.config.ANYTHING_LLM_URL | quote }}
  ANYTHING_LLM_ADMIN_USER: {{ .Values.sso.config.ANYTHING_LLM_ADMIN_USER | quote }}
  ANYTHING_LLM_VERIFY_SSL: {{ .Values.sso.config.ANYTHING_LLM_VERIFY_SSL | quote }}
{{- end }} 