"""Initial tables from SQLModel entities

Revision ID: 883e33cb5cf8
Revises:
Create Date: 2025-07-22 11:27:20.766845

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "883e33cb5cf8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        table_name="anythingllm_user",
        columns=[
            sa.Column("keycloak_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("internal_id", sqlmodel.sql.sqltypes.Integer(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint("keycloak_id"),
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anythingllm_user")
    # ### end Alembic commands ###
